-- Create the data_scraping_instagram table
create table
  public.data_scraping_instagram (
    id bigint generated by default as identity not null,
    "inputUrl" text not null,
    username text null,
    "followersCount" text null,
    "followsCount" text null,
    biography text null,
    "postsCount" text null,
    "highlightReelCount" text null,
    "igtvVideoCount" text null,
    "latestPostsTotal" text null,
    "latestPostsLikes" text null,
    "latestPostsComments" text null,
    "Url" text null,
    "User_Id" text null,
    gmail text null,
    created_at timestamp with time zone default timezone('utc'::text, now()) null,
    constraint data_scraping_instagram_pkey primary key (id)
  ) tablespace pg_default; 